nameOverride: nfs-provisioner
replicaCount: 1
strategyType: Recreate

image:
  repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
  tag: v4.0.2
  pullPolicy: IfNotPresent
imagePullSecrets: []

nfs:
  server: 127.0.0.1
  path: /srv/nfs/nextcloud
  mountOptions:
  volumeName: nfs-provisioner
  reclaimPolicy: Retain

storageClass:
  create: true

  defaultClass: true

  name: nfs-client

  allowVolumeExpansion: true

  reclaimPolicy: Delete

  archiveOnDelete: true

  onDelete:

  pathPattern:

  accessModes: ReadWriteOnce

  volumeBindingMode: Immediate

  annotations: {}

leaderElection:
  enabled: true

rbac:
  create: true

podSecurityPolicy:
  enabled: false

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

serviceAccount:
  create: true

  annotations: {}

  name:

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

podDisruptionBudget:
  enabled: false
  maxUnavailable: 1
