#!/bin/bash
set -e

export PATH=$PATH:/usr/local/bin

echo
echo "For quick setup just launch:"
echo "	bash /usr/local/nextcloud/deploy.sh"
echo
echo
echo "For remove setup launch:"
echo "	bash /usr/local/nextcloud/remove.sh"
echo
