apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nextcloud
  namespace: nextcloud
provisioner: nfs.csi.k8s.io
parameters:
  server: 127.0.0.1
  share: /srv/nfs/nextcloud
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
  - noatime
  - async
